import { StyleSheet } from 'react-native';

// Index/Timer Screen Styles
export const indexStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: "#000000",
    },
    emptyText: {
        fontSize: 20,
        fontWeight: "bold",
        textAlign: "center",
        marginTop: 50,
        color: "#ffffff",
    },
    emptySubText: {
        fontSize: 16,
        textAlign: "center",
        marginTop: 10,
        color: "#888888",
    },
    categoryContainer: {
        marginBottom: 16,
        backgroundColor: "#000000",
        borderRadius: 16,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "#333333",
    },
    categoryHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 16,
        backgroundColor: "#000000",
    },
    categoryHeaderContent: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    categoryTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#ffffff",
        marginRight: 8,
    },
    categoryCount: {
        fontSize: 12,
        color: "#888888",
        backgroundColor: "#333333",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 10,
        fontWeight: "500",
    },
    chevronIcon: {
        opacity: 0.8,
    },
    bulkActions: {
        flexDirection: "row",
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 8,
        backgroundColor: "#000000",
    },
    bulkButton: {
        backgroundColor: "#333333",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        flex: 1,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#555555",
    },
    bulkButtonText: {
        color: "#ffffff",
        fontSize: 12,
        fontWeight: "500",
    },
    timersContainer: {
        paddingHorizontal: 16,
        paddingBottom: 16,
        gap: 12,
        backgroundColor: "#000000",
    },
    timerCard: {
        backgroundColor: "#000000",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#333333",
    },
    timerHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    timerInfo: {
        flex: 1,
    },
    timerNameContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 4,
    },
    timerName: {
        fontSize: 16,
        fontWeight: "600",
        color: "#ffffff",
        marginRight: 8,
    },
    alertIcon: {
        marginLeft: 4,
    },
    timerTime: {
        fontSize: 20,
        fontWeight: "300",
        color: "#ffffff",
        fontFamily: "monospace",
    },
    timerStatus: {
        fontSize: 11,
        color: "#aaaaaa",
        textTransform: "capitalize",
        backgroundColor: "#333333",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
        fontWeight: "500",
    },
    progressBarContainer: {
        height: 4,
        backgroundColor: "#333333",
        borderRadius: 2,
        marginVertical: 12,
        overflow: "hidden",
    },
    progressBar: {
        height: "100%",
        backgroundColor: "#ffffff",
        borderRadius: 2,
    },
    timerControls: {
        flexDirection: "row",
        justifyContent: "center",
        gap: 8,
    },
    controlButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#ffffff",
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        minWidth: 70,
        justifyContent: "center",
        gap: 4,
    },
    startButton: {
        backgroundColor: "#ffffff",
    },
    pauseButton: {
        backgroundColor: "#888888",
    },
    resetButton: {
        backgroundColor: "#666666",
    },
    deleteButton: {
        backgroundColor: "#444444",
    },
    controlButtonText: {
        color: "#000000",
        fontSize: 12,
        fontWeight: "600",
    },
    deleteButtonText: {
        color: "#ffffff",
        fontSize: 12,
        fontWeight: "600",
    },
    filterIndicator: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#1a1a1a",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 8,
        marginBottom: 16,
        gap: 8,
        borderWidth: 1,
        borderColor: "#333333",
    },
    filterText: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "500",
        flex: 1,
    },
    filterSection: {
        marginBottom: 16,
        position: "relative",
        zIndex: 1000,
    },
    backdrop: {
        position: "absolute",
        top: 0,
        left: -16,
        right: -16,
        bottom: -1000,
        zIndex: 999,
    },
    filterToggle: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#1a1a1a",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 8,
        gap: 12,
        borderWidth: 1,
        borderColor: "#333333",
    },
    filterToggleText: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "500",
        flex: 1,
    },
    filterDropdown: {
        position: "absolute",
        top: "100%",
        left: 0,
        right: 0,
        backgroundColor: "#1a1a1a",
        borderRadius: 8,
        marginTop: 4,
        borderWidth: 1,
        borderColor: "#333333",
        shadowColor: "#000000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
        zIndex: 1001,
    },
    filterOption: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#333333",
    },
    filterOptionSelected: {
        backgroundColor: "#ffffff",
    },
    filterOptionText: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "500",
        flex: 1,
    },
    filterOptionTextSelected: {
        color: "#000000",
        fontWeight: "600",
    },
    clearFilterOption: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 12,
        backgroundColor: "#2a1a1a",
        borderTopWidth: 1,
        borderTopColor: "#444444",
    },
    clearFilterText: {
        color: "#ff6b6b",
        fontSize: 14,
        fontWeight: "500",
        flex: 1,
    },
    notificationWarning: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#2a1a1a",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
        marginTop: 8,
        gap: 8,
        borderWidth: 1,
        borderColor: "#ff6b6b",
    },
    notificationWarningText: {
        color: "#ff6b6b",
        fontSize: 12,
        fontWeight: "500",
        flex: 1,
    },
});

// Modal/Add Timer Screen Styles
export const modalStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: "#000000",
    },
    formContainer: {
        flex: 1,
        paddingTop: 20,
    },
    title: {
        fontSize: 28,
        fontWeight: "bold",
        textAlign: "center",
        marginBottom: 40,
        color: "#ffffff",
    },
    inputContainer: {
        marginBottom: 24,
    },
    label: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 8,
        color: "#ffffff",
    },
    input: {
        borderWidth: 1,
        borderColor: "#333333",
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        backgroundColor: "#111111",
        color: "#ffffff",
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 40,
        gap: 16,
    },
    button: {
        backgroundColor: "#ffffff",
        paddingHorizontal: 32,
        paddingVertical: 16,
        borderRadius: 12,
        flex: 1,
        alignItems: "center",
    },
    buttonText: {
        color: "#000000",
        fontSize: 16,
        fontWeight: "600",
    },
    categoryContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
        marginTop: 8,
    },
    categoryButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: "#333333",
        backgroundColor: "#111111",
        alignItems: "center",
        minWidth: 80,
    },
    categoryButtonSelected: {
        borderColor: "#FFFFFF",
        backgroundColor: "#333333",
    },
    categoryButtonText: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "500",
    },
    categoryButtonTextSelected: {
        color: "#FFFFFF",
        fontWeight: "bold",
    },
    switchContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 8,
    },
    switchLabelContainer: {
        flex: 1,
        marginRight: 16,
    },
    switchDescription: {
        fontSize: 12,
        color: "#888888",
        marginTop: 4,
        lineHeight: 16,
    },
});

// History Screen Styles
export const historyStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: "#000000",
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
    },
    title: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#ffffff",
        flex: 1,
    },
    actionButtons: {
        flexDirection: "row",
        gap: 12,
        marginBottom: 20,
    },
    headerButtons: {
        flexDirection: "row",
        gap: 10,
    },
    exportButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#22c55e",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 10,
        gap: 8,
        flex: 1,
        justifyContent: "center",
    },
    clearButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#1a1a1a",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#ff6b6b",
        gap: 8,
        flex: 1,
        justifyContent: "center",
    },
    buttonText: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "600",
    },
    clearButtonText: {
        color: "#ff6b6b",
        fontSize: 14,
        fontWeight: "600",
    },
    scrollView: {
        flex: 1,
    },
    emptyText: {
        fontSize: 20,
        fontWeight: "bold",
        textAlign: "center",
        marginTop: 50,
        color: "#ffffff",
    },
    emptySubText: {
        fontSize: 16,
        textAlign: "center",
        marginTop: 10,
        color: "#888888",
    },
    historyCard: {
        backgroundColor: "#111111",
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#2a2a2a",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    historyHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 14,
    },
    historyName: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#ffffff",
        flex: 1,
        marginRight: 12,
    },
    historyCategory: {
        fontSize: 12,
        color: "#ffffff",
        backgroundColor: "#333333",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    historyDuration: {
        fontSize: 15,
        color: "#ffffff",
        marginBottom: 8,
        fontWeight: "500",
    },
    historyDate: {
        fontSize: 13,
        color: "#999999",
        fontWeight: "400",
    },
});
